### ISSUE TITLE
don't include both `QuickReplies.html` and `quickReplies.html`

### ISSUE THREAD

**Issue by jonasfj** [VictorRancesCode/flutter_dialogflow#7]
See https://github.com/dart-lang/pub/issues/2072

In general, I would discourage checking the `doc/api/` folder into source control, and I would also discourage you from having it in your folder when publishing as it gets included in the package on pub..

The problem in this case is probably (just guessing), that you renamed `quickReplies` to `QuickReplies` (or maybe you have two types with same name, only one is lowercase) and suddenly you have two files with the same name (except one is lowercase, the other is uppercase)... Such packages won't work on Windows, since the filesystem is case insensitive (case preserving).

--------

Note: if you think you actually generated documentation producing both `QuickReplies.html` and `quickReplies.html`, then please make a small test-case that reproduces this and file an issue with: https://github.com/dart-lang/dartdoc

**Comment by sigurdm** [comment]
See https://github.com/dart-lang/dartdoc/issues/1196

**Comment by VictorRancesCode** [comment]
Greetings, I have already made the update. I have deleted the doc folder and fixed some problems with the lower case, so that the same problem does not occur. =)

**Comment by jonasfj** [comment]
Cool, thanks :)
